import { LOG_MESSAGES } from './logMessages'

export const DOCUMENT_STATUS = {
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  PENDING_UPLOAD: 'PENDING_UPLOAD',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
}

export const DOCUMENT_ACTION_TYPE = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT'
}

export const APPROVE_DOCUMENT_LOG_MESSAGE = {
  APPROVE: {
    success: LOG_MESSAGES.DOCUMENT_APPROVE_SUCCESS,
    error: LOG_MESSAGES.DOCUMENT_APPROVE_ERROR
  },
  REJECT: {
    success: LOG_MESSAGES.DOCUMENT_REJECT_SUCCESS,
    error: LOG_MESSAGES.DOCUMENT_REJECT_ERROR
  }
}
