export const ROLE = {
  TXC_ACCOUNT_ADMIN: 'TXC_ACCOUNT_ADMIN',
  TXC_SUPER_ADMIN: 'TXC_SUPER_ADMIN',
  TXC_OPERATION: 'TXC_OPERATION',
  TXC_BACK_OFFICE: 'TXC_BACK_OFFICE',
  DELOITTE_MANAGER_ADMIN: 'DELOITTE_MANAGER_ADMIN',
  DELOITTE_PARTNER_ADMIN: 'DELOITTE_PARTNER_ADMIN',
  DELOITTE_CONSULTANT: 'DELOITTE_CONSULTANT',
  NOTARY_ADMIN: 'NOTARY_ADMIN',
  MEMBER_SELLER: 'MEMBER_SELLER',
  MEMBER_BUYER_DERIVATIVE_ACCOUNT_ADMIN: 'MEMBER_BUYER_DERIVATIVE_ACCOUNT_ADMIN',
  MEMBER_BUYER_DERIVATIVE: 'MEMBER_BUYER_DERIVATIVE',
  MEMBER_BUYER_CLAIM_ACCOUNT_ADMIN: 'MEMBER_BUYER_CLAIM_ACCOUNT_ADMIN',
  MEMBER_BUYER_CLAIM: 'MEMBER_BUYER_CLAIM',
  MEMBER_BUYER_ALL: 'MEMBER_BUYER_ALL',
  MEMBER_BUYER_ALL_ACCOUNT_ADMIN: 'MEMBER_BUYER_ALL_ACCOUNT_ADMIN',
  BROKER: 'BROKER'
}

export const ROLE_DESCRIPTION = {
  MEMBER_SELLER: 'Seller',
  MEMBER_BUYER_DERIVATIVE_ACCOUNT_ADMIN: 'Buyer Derivative (Account Admin)',
  MEMBER_BUYER_DERIVATIVE: 'Buyer Derivative',
  MEMBER_BUYER_CLAIM_ACCOUNT_ADMIN: 'Buyer Claim (Account Admin)',
  MEMBER_BUYER_CLAIM: 'Buyer Claim',
  MEMBER_BUYER_ALL: 'Buyer All',
  MEMBER_BUYER_ALL_ACCOUNT_ADMIN: 'Buyer All (Account Admin)',
  BROKER: 'Partner'
}

export const ROLE_TYPE = {
  ADMIN: 'admin',
  MEMBER: 'member'
}
