const formatMember = {
  join: (data) => ({
    type: data?.companyInformation?.memberType || '',
    categoryClient: data?.companyInformation?.categoryClient || '',
    registeredEmailPec: data?.companyInformation?.registeredEmail || '',
    officialAddress: data?.companyInformation?.officialAddress || '',
    street: data?.companyInformation?.street || '',
    zipCode: data?.companyInformation?.postalCode || '',
    country: data?.companyInformation?.country || '',
    registeredNumber: data?.companyInformation?.registeredNumber || '',
    companyName: data?.companyInformation?.companyName || '',
    vatNumber: data?.companyInformation?.vatNumber || '',
    authority: data?.companyInformation?.authority || '',
    beneficialOwner: data?.companyInformation?.documents?.beneficialOwner || '',
    groupChart: data?.companyInformation?.documents?.groupChartShareholding || '',
    companyRegistrationReport: data?.companyInformation?.documents?.companyRegistrationReport || '',
    statute: data?.companyInformation?.documents?.statute || '',
    lastFinancialStatement: data?.companyInformation?.documents?.lastFinancialStatement || '',
    legalRepresentativeFirstName: data?.legalRepresentative?.firstName || '',
    legalRepresentativeSurname: data?.legalRepresentative?.surname || '',
    legalRepresentativePhoneMobile: data?.legalRepresentative?.mobilePhone || '',
    legalRepresentativePhoneLandline: data?.legalRepresentative?.landline || '',
    legalRepresentativeEmail: data?.legalRepresentative?.email || '',
    legalRepresentativeCompanyFunction: data?.legalRepresentative?.companyFunction || '',
    legalRepresentativeCompanyTitle: data?.legalRepresentative?.companyTitle || '',
    legalRepresentativePrivacy: data?.legalRepresentative?.documents?.privacy || '',
    legalRepresentativeIdCard: data?.legalRepresentative?.documents?.identityCardPassword || '',
    legalRepresentativeFiscalCode: data?.legalRepresentative?.documents?.fiscalCode || '',
    beneficialOwnerFirstName: data?.beneficialOwner?.firstName || '',
    beneficialOwnerSurname: data?.beneficialOwner?.surname || '',
    beneficialOwnerPhoneMobile: data?.beneficialOwner?.mobilePhone || '',
    beneficialOwnerPhoneLandline: data?.beneficialOwner?.landline || '',
    beneficialOwnerEmail: data?.beneficialOwner?.email || '',
    beneficialOwnerCompanyFunction: data?.beneficialOwner?.companyFunction || '',
    beneficialOwnerCompanyTitle: data?.beneficialOwner?.companyTitle || '',
    beneficialOwnerPrivacy: data?.beneficialOwner?.documents?.privacy || '',
    beneficialOwnerIdCard: data?.beneficialOwner?.documents?.identityCardPassword || '',
    beneficialOwnerFiscalCode: data?.beneficialOwner?.documents?.fiscalCode || '',
    operativeInfoFirstName: data?.operativeInformation?.firstName || '',
    operativeInfoSurname: data?.operativeInformation?.surname || '',
    operativeInfoPhoneMobile: data?.operativeInformation?.mobilePhone || '',
    operativeInfoPhoneLandline: data?.operativeInformation?.landline || '',
    operativeInfoEmail: data?.operativeInformation?.email || '',
    operativeInfoCompanyFunction: data?.operativeInformation?.companyFunction || '',
    operativeInfoCompanyTitle: data?.operativeInformation?.companyTitle || '',
    operativeInfoPoa: data?.operativeInformation?.documents?.powerAttorney || '',
    operativeInfoIdCard: data?.operativeInformation?.documents?.identityCardPassword || '',
    operativeInfoFiscalCode: data?.operativeInformation?.documents?.fiscalCode || '',
    operativeInfoPrivacy: data?.operativeInformation?.documents?.operativeInfoPrivacy || '',
    registerConcluded: data?.registerConcluded || false,
  }),
  separate: (data) => ({
    companyInformation: {
      memberType: data?.type || '',
      categoryClient: data?.categoryClient || '',
      registeredEmail: data?.registeredEmailPec || '',
      officialAddress: data?.officialAddress || '',
      street: data?.street || '',
      postalCode: data?.zipCode || '',
      country: data?.country || '',
      registeredNumber: data?.registeredNumber || '',
      companyName: data?.companyName || '',
      vatNumber: data?.vatNumber || '',
      authority: data?.authority || '',
      documents: {
        beneficialOwner: data?.beneficialOwner || '',
        groupChartShareholding: data?.groupChart || '',
        companyRegistrationReport: data?.companyRegistrationReport || '',
        statute: data?.statute || '',
        lastFinancialStatement: data?.lastFinancialStatement || '',
      }
    },
    legalRepresentative: {
      firstName: data?.legalRepresentativeFirstName || '',
      surname: data?.legalRepresentativeSurname || '',
      mobilePhone: data?.legalRepresentativePhoneMobile || '',
      landline: data?.legalRepresentativePhoneLandline || '',
      email: data?.legalRepresentativeEmail || '',
      companyFunction: data?.legalRepresentativeCompanyFunction || '',
      companyTitle: data?.legalRepresentativeCompanyTitle || '',
      documents: {
        privacy: data?.legalRepresentativePrivacy || '',
        identityCardPassword: data?.legalRepresentativeIdCard || '',
        fiscalCode: data?.legalRepresentativeFiscalCode || '',
      }
    },
    beneficialOwner: {
      firstName: data?.beneficialOwnerFirstName || '',
      surname: data?.beneficialOwnerSurname || '',
      mobilePhone: data?.beneficialOwnerPhoneMobile || '',
      landline: data?.beneficialOwnerPhoneLandline || '',
      email: data?.beneficialOwnerEmail || '',
      companyFunction: data?.beneficialOwnerCompanyFunction || '',
      companyTitle: data?.beneficialOwnerCompanyTitle || '',
      documents: {
        privacy: data?.beneficialOwnerPrivacy || '',
        identityCardPassword: data?.beneficialOwnerIdCard || '',
        fiscalCode: data?.beneficialOwnerFiscalCode || '',
      }
    },
    operativeInformation: {
      firstName: data?.operativeInfoFirstName || '',
      surname: data?.operativeInfoSurname || '',
      mobilePhone: data?.operativeInfoPhoneMobile || '',
      landline: data?.operativeInfoPhoneLandline || '',
      email: data?.operativeInfoEmail || '',
      companyFunction: data?.operativeInfoCompanyFunction || '',
      companyTitle: data?.operativeInfoCompanyTitle || '',
      documents: {
        powerAttorney: data?.operativeInfoPoa || '',
        identityCardPassword: data?.operativeInfoIdCard || '',
        fiscalCode: data?.operativeInfoFiscalCode || '',
        operativeInfoPrivacy: data?.operativeInfoPrivacy || ''
      }
    },
    registerApproved: data?.registerApproved || false,
    registerConcluded: data?.registerConcluded || false,
  })
}

export default formatMember
