/**
 * layout
 */
// simple defaults we can update these based on the gogo sass
const SPACING_BASE = 8

const ZINDEX_ABYSS = '-9999'
const ZINDEX_FLOOR = '1'
const ZINDEX_DROPDOWN = '1010'
const ZINDEX_STICKY = '1020'
const ZINDEX_FIXED = '1030'
const ZINDEX_SCRIM = '1040'
const ZINDEX_MODAL = '1050'
const ZINDEX_POPOVER = '1060'
const ZINDEX_TOOLTIP = '1070'

const CORNER_RADIUS_SHARP = '2px' // spacingScale(0.5)
const CORNER_RADIUS_INPUT = '4px' // spacingScale(1)
const CORNER_RADIUS_CARD_SM = '4px'
const CORNER_RADIUS_CARD_DEFAULT = '6px'
const CORNER_RADIUS_CARD_LG = '8px'
const CORNER_RADIUS_MAX = '90000px'

export {
  SPACING_BASE,
  ZINDEX_ABYSS,
  ZINDEX_FLOOR,
  ZINDEX_DROPDOWN,
  ZINDEX_STICKY,
  ZINDEX_FIXED,
  ZINDEX_SCRIM,
  ZINDEX_MODAL,
  ZINDEX_POPOVER,
  ZINDEX_TOOLTIP,
  CORNER_RADIUS_SHARP,
  CORNER_RADIUS_INPUT,
  CORNER_RADIUS_CARD_SM,
  CORNER_RADIUS_CARD_DEFAULT,
  CORNER_RADIUS_CARD_LG,
  CORNER_RADIUS_MAX
}
